-- 코드를 입력하세요
SELECT
    A.PRODUCT_CODE as PRODUCT_CODE, SUM(A.PRICE*B.SALES_AMOUNT) as SALES
FROM PRODUCT as A
JOIN OFFLINE_SALE as B ON A.PRODUCT_ID=B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY
    SUM(A.PRICE*B.SALES_AMOUNT) DESC, A.PRODUCT_CODE